import "../styles/global.css"

export const metadata = {
  title: 'JH PORTFOLIO',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
